# Generated by Django 5.1.1 on 2024-10-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AddField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo_images/'),
        ),
    ]
