# Generated by Django 5.1.1 on 2024-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='promo',
            name='priority_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='time_offer',
            field=models.JSONField(default={'Friday': '9:00AM\u2009–\u20093:00PM', 'Monday': '9:00AM\u2009–\u20093:00PM', 'Saturday': 'Closed', 'Sunday': 'Closed', 'Thursday': '9:00AM\u2009–\u20093:00PM', 'Tuesday': '9:00AM\u2009–\u20093:00PM', 'Wednesday': '9:00AM\u2009–\u20093:00PM'}),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='operating_hours',
            field=models.JSONField(default={'Friday': '9:00AM\u2009–\u20093:00PM', 'Monday': '9:00AM\u2009–\u20093:00PM', 'Saturday': 'Closed', 'Sunday': 'Closed', 'Thursday': '9:00AM\u2009–\u20093:00PM', 'Tuesday': '9:00AM\u2009–\u20093:00PM', 'Wednesday': '9:00AM\u2009–\u20093:00PM'}),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='priority_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
