# Generated by Django 5.1.1 on 2024-10-07 21:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menu_priority_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
