# Generated by Django 5.1.1 on 2024-10-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_restaurant_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='object_id',
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.menu'),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.restaurant'),
        ),
    ]
