# Generated by Django 5.1.1 on 2024-10-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_addonoption_menu_item_alter_addonoption_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('category_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('menu', 'Menu')], max_length=50)),
                ('priority_index', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'menu'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='core.category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'restaurant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='core.category'),
        ),
    ]
