# Generated by Django 5.1.1 on 2024-10-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_menu_category_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_type',
        ),
    ]
