# Generated by Django 5.1.1 on 2024-10-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='promo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='minimum_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='target_audience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='province',
            field=models.CharField(blank=True, choices=[('OT', 'Out of Canada'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='social_media_links',
            field=models.JSONField(default={'fb': '', 'instagram': '', 'linkedin': '', 'twitter': ''}),
        ),
        migrations.AlterField(
            model_name='promo',
            name='time_offer',
            field=models.JSONField(default={'Friday': '9:00AM – 3:00PM', 'Monday': '9:00AM – 3:00PM', 'Saturday': 'Closed', 'Sunday': 'Closed', 'Thursday': '9:00AM – 3:00PM', 'Tuesday': '9:00AM – 3:00PM', 'Wednesday': '9:00AM – 3:00PM'}),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='operating_hours',
            field=models.JSONField(default={'Friday': '9:00AM – 3:00PM', 'Monday': '9:00AM – 3:00PM', 'Saturday': 'Closed', 'Sunday': 'Closed', 'Thursday': '9:00AM – 3:00PM', 'Tuesday': '9:00AM – 3:00PM', 'Wednesday': '9:00AM – 3:00PM'}),
        ),
    ]
