# Generated by Django 5.1.1 on 2024-11-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_promo_menu_restaurant_slug_alter_promo_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='code',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='minimum_order',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='priority_index',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='time_offer',
        ),
        migrations.AddField(
            model_name='promo',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
