# Generated by Django 5.1.1 on 2024-10-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_restaurant_opening_hours_promo_priority_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='priority_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
