# Generated by Django 5.1.1 on 2024-10-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_addoncategory_addonoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonoption',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_addon_options', to='core.menu'),
        ),
        migrations.AlterField(
            model_name='addonoption',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
