# Generated by Django 5.1.1 on 2024-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_promo_code_promo_discount_type_promo_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'restaurant'}, related_name='restaurants', to='core.category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_type',
            field=models.CharField(choices=[('dine-in', 'Dine-in'), ('takeout', 'Takeout'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
