# Generated by Django 5.1.1 on 2024-11-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_restaurant_category_restaurant_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_of_user',
            field=models.CharField(choices=[('restaurant_owner', 'Restaurant Owner'), ('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
