# Generated by Django 5.1.1 on 2024-12-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_promo_menu_menu_promos_promo_promo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('restaurant', 'Restaurant'), ('dineease', 'DineEase')], default='restaurant', max_length=20),
        ),
    ]
