# Generated by Django 5.1.1 on 2024-12-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_coordinates_userprofile_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='usage_limit_per_customer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
