# Generated by Django 5.1.1 on 2024-12-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_promo_usage_limit_per_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
