# Generated by Django 5.1.1 on 2024-12-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_restaurant_status_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
