# Generated by Django 5.1.1 on 2024-12-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('premium', 'Premium'), ('archived', 'Archived')], default='pending', max_length=10),
        ),
    ]
