# Generated by Django 5.1.1 on 2025-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_category_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
