# Generated by Django 5.1.1 on 2025-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_verificationcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('unavailable', 'Unavailable')], default='active', max_length=12),
        ),
    ]
