# Generated by Django 5.1.1 on 2024-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_order_addon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
