# Generated by Django 5.1.1 on 2024-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('OT', 'Out of Canada'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=2, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as a percentage (e.g., 5 for 5%)', max_digits=5)),
                ('service_fee_thresholds', models.JSONField(default=dict, help_text="Define thresholds for service fees. E.g., {'<30': 2, '30-50': 3, '50-100': 4.29, '>=100': 6.29}")),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='service_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
