# Generated by Django 5.1.1 on 2024-12-25 10:29

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_tax_rename_tax_order_service_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='service_fee_thresholds',
            field=models.JSONField(default=payments.models.default_service_fee_thresholds, help_text="Define thresholds for service fees. E.g., {'<30': 2, '30-50': 3, '50-100': 4.29, '>=100': 6.29}"),
        ),
    ]
