# Generated by Django 5.1.1 on 2024-12-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_restaurant_province_alter_userprofile_province'),
        ('payments', '0010_remove_order_promo_order_promos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promos',
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.promo'),
        ),
    ]
