# Generated by Django 5.1.1 on 2024-12-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_order_promos_order_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='promo',
            new_name='promos',
        ),
    ]
