# Generated by Django 5.1.1 on 2024-12-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_restaurant_province_alter_userprofile_province'),
        ('payments', '0012_rename_promo_order_promos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promos',
        ),
        migrations.AddField(
            model_name='order',
            name='promos',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.promo'),
        ),
    ]
