# Generated by Django 5.1.1 on 2024-12-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_remove_order_promos_order_promos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promousage',
            unique_together=set(),
        ),
    ]
