# Generated by Django 5.1.1 on 2024-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_promousage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the tax rate is active.'),
        ),
    ]
