# Generated by Django 5.1.1 on 2024-12-30 16:31

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_tax_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='service_fee_thresholds',
            field=models.JSONField(default=payments.models.default_service_fee_thresholds, help_text="Define thresholds for service fees. E.g., {'<25': 0.49, '25-50': 0.99, '50-75': 1.49, '>=100': 2.49}"),
        ),
    ]
