# Generated by Django 5.1.1 on 2024-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_payment_card_brand_payment_card_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_exp_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_exp_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('mobile_payment', 'Mobile Payment'), ('wallet', 'Wallet')], max_length=50),
        ),
    ]
