# Generated by Django 5.1.1 on 2024-12-31 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_category_restaurant'),
        ('payments', '0019_order_platform_revenue_order_restaurant_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verification_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.verificationcode'),
        ),
    ]
