# Generated by Django 5.1.1 on 2025-01-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_order_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_time']},
        ),
    ]
