# Generated by Django 5.1.1 on 2025-01-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_menu_status'),
        ('payments', '0021_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verification_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='core.verificationcode'),
        ),
    ]
