# Use the latest LTS Node.js image
FROM node:lts

# Set working directory
WORKDIR /app

# Expose the Nuxt development server port
EXPOSE 3000

# Start the Nuxt application in development mode
CMD ["npm", "run", "dev"]